-- AlterTable
ALTER TABLE "Bid" ADD COLUMN "mrp" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Bid" ADD COLUMN "expiry" TIMESTAMP(3);
ALTER TABLE "Bid" ADD COLUMN "isCustomBid" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Bid" ADD COLUMN "customQuantity" INTEGER;
ALTER TABLE "Bid" ADD COLUMN "customPrice" DOUBLE PRECISION;
ALTER TABLE "Bid" ADD COLUMN "customExpiry" TIMESTAMP(3);
